package dreamschool.csourse.chapter08;

public class Account {

		private String number;
		private int Balance;
		private double interestRate;
		
		public String getNumber1() {
			return number;
		}
		public int getBalance() {
			return Balance;
		}
		public double getInterestRate() {
			return interestRate;
		}
		public Account(String number, int balance, double interestRate) {
			this.number = number;
			Balance = balance;
			this.interestRate = interestRate;
		}
		
		public int calculateInterest() {
			int interest = (int)(Balance * this.interestRate / 100);
			Balance +=interest;
			return interest;
		}
		
		public String getNumber() {
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatev
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatevvv
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatev
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatev
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatev
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRateㅍㅍ
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRateㅍㅍ
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRateㅍ
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRateㅍ
			setInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRatesetInterestRate
			
		}
		
		
		

	}
